name: 'Format Code'

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # Needs access to push to main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Node
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_pluggins: "prettier-plugin-astro"
          prettier_options: --write **/*.{js,md,astro,jsx}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '💚 Code format'
          branch: ${{ github.head_ref }}
          commit_user_name: DiegoMarty
          commit_user_email: contacto@diegomarty.com
